# Generated by Django 4.1.7 on 2023-08-25 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('permanentaddress', models.CharField(max_length=100)),
                ('residencialaddress', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourcesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(choices=[('BSCCSIT', 'BSCCSIT'), ('BIT', 'BIT'), ('BCA', 'BCA'), ('B.TECH', 'B.TECH'), ('BBS', 'BBS'), ('BBA', 'BBA'), ('B.ED', 'B.ED'), ('+2 SCIENCE', '+2 SCIENCE'), ('+2 MANAGEMENT', '+2 MANAGEMENT'), ('+2 EDUCATION', '+2 EDUCATION')], max_length=100)),
                ('shortdetail', models.CharField(max_length=300)),
                ('year', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=100)),
                ('semester', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester'), ('Third Semester', 'Third Semester'), ('Fourth Semester', 'Fourth Semester'), ('Fifth Semester', 'Fifth Semester'), ('Six Semester', 'Six Semester'), ('Seven Semester', 'Seven Semester'), ('Eight Semester', 'Eight Semester')], max_length=100)),
                ('subject', models.CharField(max_length=160)),
                ('oldquestion', models.FileField(upload_to='notebook/media')),
                ('oldquestionyear', models.DateField()),
                ('syllabus', models.FileField(upload_to='notebook/file')),
                ('syllabuspublishdate', models.DateTimeField(auto_now_add=True)),
                ('note', models.FileField(upload_to='notebook/note')),
                ('notepublishdate', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.profile')),
            ],
        ),
    ]
