# Generated by Django 4.1.7 on 2023-08-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_courcesmodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courcesmodel',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notebook.profile'),
        ),
    ]
