# Generated by Django 4.1.7 on 2023-08-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_courcesmodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courcesmodel',
            name='cname',
            field=models.CharField(choices=[('BSCCSIT', 'BSCCSIT'), ('BSC', 'BSC'), ('BIT', 'BIT'), ('BCA', 'BCA'), ('B.TECH', 'B.TECH'), ('BBS', 'BBS'), ('BBA', 'BBA'), ('B.ED', 'B.ED'), ('+2 SCIENCE', '+2 SCIENCE'), ('+2 MANAGEMENT', '+2 MANAGEMENT'), ('+2 EDUCATION', '+2 EDUCATION')], max_length=100),
        ),
    ]
